/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as PrivateRouteImport } from './routes/_private'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as SocialRouteImport } from './routes/_social'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as MarketingAboutRouteImport } from './routes/_marketing/about'
import { Route as PrivateGroupsRouteImport } from './routes/_private.groups'
import { Route as PrivateInboxRouteImport } from './routes/_private.inbox'
import { Route as PrivateModerationRouteImport } from './routes/_private.moderation'
import { Route as PrivateNotificationsRouteImport } from './routes/_private.notifications'
import { Route as PrivateSettingsRouteImport } from './routes/_private.settings'
import { Route as PublicBannedRouteImport } from './routes/_public/banned'
import { Route as PublicChildSafetyRouteImport } from './routes/_public/child-safety'
import { Route as PublicLoginRouteImport } from './routes/_public/login'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicRegisterRouteImport } from './routes/_public/register'
import { Route as PublicSocialRouteImport } from './routes/_public/social'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicTiersRouteImport } from './routes/_public/tiers'
import { Route as SocialFeedRouteImport } from './routes/_social/feed'
import { Route as SocialNotesRouteImport } from './routes/_social/notes'
import { Route as GroupsTagRouteImport } from './routes/groups.$tag'
import { Route as PrivateInboxMessageIdRouteImport } from './routes/_private.inbox_.$messageId'
import { Route as SocialPostIdRouteImport } from './routes/_social/post.$id'
import { Route as SocialToUsernameRouteImport } from './routes/_social/to.$username'
import { Route as SocialUserUsernameRouteImport } from './routes/_social/user.$username'
import { Route as GroupsTagIndexRouteImport } from './routes/groups.$tag.index'
import { Route as GroupsTagChatRouteImport } from './routes/groups.$tag.chat'

const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateRoute = PrivateRouteImport.update({
  id: '/_private',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const SocialRoute = SocialRouteImport.update({
  id: '/_social',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingAboutRoute = MarketingAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => MarketingRoute,
} as any)
const PrivateGroupsRoute = PrivateGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateInboxRoute = PrivateInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateModerationRoute = PrivateModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateNotificationsRoute = PrivateNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => PrivateRoute,
} as any)
const PrivateSettingsRoute = PrivateSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PrivateRoute,
} as any)
const PublicBannedRoute = PublicBannedRouteImport.update({
  id: '/banned',
  path: '/banned',
  getParentRoute: () => PublicRoute,
} as any)
const PublicChildSafetyRoute = PublicChildSafetyRouteImport.update({
  id: '/child-safety',
  path: '/child-safety',
  getParentRoute: () => PublicRoute,
} as any)
const PublicLoginRoute = PublicLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicRegisterRoute = PublicRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSocialRoute = PublicSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTiersRoute = PublicTiersRouteImport.update({
  id: '/tiers',
  path: '/tiers',
  getParentRoute: () => PublicRoute,
} as any)
const SocialFeedRoute = SocialFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => SocialRoute,
} as any)
const SocialNotesRoute = SocialNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => SocialRoute,
} as any)
const GroupsTagRoute = GroupsTagRouteImport.update({
  id: '/groups/$tag',
  path: '/groups/$tag',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivateInboxMessageIdRoute = PrivateInboxMessageIdRouteImport.update({
  id: '/inbox_/$messageId',
  path: '/inbox/$messageId',
  getParentRoute: () => PrivateRoute,
} as any)
const SocialPostIdRoute = SocialPostIdRouteImport.update({
  id: '/post/$id',
  path: '/post/$id',
  getParentRoute: () => SocialRoute,
} as any)
const SocialToUsernameRoute = SocialToUsernameRouteImport.update({
  id: '/to/$username',
  path: '/to/$username',
  getParentRoute: () => SocialRoute,
} as any)
const SocialUserUsernameRoute = SocialUserUsernameRouteImport.update({
  id: '/user/$username',
  path: '/user/$username',
  getParentRoute: () => SocialRoute,
} as any)
const GroupsTagIndexRoute = GroupsTagIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GroupsTagRoute,
} as any)
const GroupsTagChatRoute = GroupsTagChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => GroupsTagRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/groups': typeof PrivateGroupsRoute
  '/inbox': typeof PrivateInboxRoute
  '/moderation': typeof PrivateModerationRoute
  '/notifications': typeof PrivateNotificationsRoute
  '/settings': typeof PrivateSettingsRoute
  '/banned': typeof PublicBannedRoute
  '/child-safety': typeof PublicChildSafetyRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/register': typeof PublicRegisterRoute
  '/social': typeof PublicSocialRoute
  '/terms': typeof PublicTermsRoute
  '/tiers': typeof PublicTiersRoute
  '/feed': typeof SocialFeedRoute
  '/notes': typeof SocialNotesRoute
  '/groups/$tag': typeof GroupsTagRouteWithChildren
  '/inbox/$messageId': typeof PrivateInboxMessageIdRoute
  '/post/$id': typeof SocialPostIdRoute
  '/to/$username': typeof SocialToUsernameRoute
  '/user/$username': typeof SocialUserUsernameRoute
  '/groups/$tag/chat': typeof GroupsTagChatRoute
  '/groups/$tag/': typeof GroupsTagIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof MarketingIndexRoute
  '/about': typeof MarketingAboutRoute
  '/groups': typeof PrivateGroupsRoute
  '/inbox': typeof PrivateInboxRoute
  '/moderation': typeof PrivateModerationRoute
  '/notifications': typeof PrivateNotificationsRoute
  '/settings': typeof PrivateSettingsRoute
  '/banned': typeof PublicBannedRoute
  '/child-safety': typeof PublicChildSafetyRoute
  '/login': typeof PublicLoginRoute
  '/privacy': typeof PublicPrivacyRoute
  '/register': typeof PublicRegisterRoute
  '/social': typeof PublicSocialRoute
  '/terms': typeof PublicTermsRoute
  '/tiers': typeof PublicTiersRoute
  '/feed': typeof SocialFeedRoute
  '/notes': typeof SocialNotesRoute
  '/inbox/$messageId': typeof PrivateInboxMessageIdRoute
  '/post/$id': typeof SocialPostIdRoute
  '/to/$username': typeof SocialToUsernameRoute
  '/user/$username': typeof SocialUserUsernameRoute
  '/groups/$tag/chat': typeof GroupsTagChatRoute
  '/groups/$tag': typeof GroupsTagIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/_private': typeof PrivateRouteWithChildren
  '/_public': typeof PublicRouteWithChildren
  '/_social': typeof SocialRouteWithChildren
  '/_marketing/about': typeof MarketingAboutRoute
  '/_private/groups': typeof PrivateGroupsRoute
  '/_private/inbox': typeof PrivateInboxRoute
  '/_private/moderation': typeof PrivateModerationRoute
  '/_private/notifications': typeof PrivateNotificationsRoute
  '/_private/settings': typeof PrivateSettingsRoute
  '/_public/banned': typeof PublicBannedRoute
  '/_public/child-safety': typeof PublicChildSafetyRoute
  '/_public/login': typeof PublicLoginRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/register': typeof PublicRegisterRoute
  '/_public/social': typeof PublicSocialRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/tiers': typeof PublicTiersRoute
  '/_social/feed': typeof SocialFeedRoute
  '/_social/notes': typeof SocialNotesRoute
  '/groups/$tag': typeof GroupsTagRouteWithChildren
  '/_marketing/': typeof MarketingIndexRoute
  '/_private/inbox_/$messageId': typeof PrivateInboxMessageIdRoute
  '/_social/post/$id': typeof SocialPostIdRoute
  '/_social/to/$username': typeof SocialToUsernameRoute
  '/_social/user/$username': typeof SocialUserUsernameRoute
  '/groups/$tag/chat': typeof GroupsTagChatRoute
  '/groups/$tag/': typeof GroupsTagIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/groups'
    | '/inbox'
    | '/moderation'
    | '/notifications'
    | '/settings'
    | '/banned'
    | '/child-safety'
    | '/login'
    | '/privacy'
    | '/register'
    | '/social'
    | '/terms'
    | '/tiers'
    | '/feed'
    | '/notes'
    | '/groups/$tag'
    | '/inbox/$messageId'
    | '/post/$id'
    | '/to/$username'
    | '/user/$username'
    | '/groups/$tag/chat'
    | '/groups/$tag/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/groups'
    | '/inbox'
    | '/moderation'
    | '/notifications'
    | '/settings'
    | '/banned'
    | '/child-safety'
    | '/login'
    | '/privacy'
    | '/register'
    | '/social'
    | '/terms'
    | '/tiers'
    | '/feed'
    | '/notes'
    | '/inbox/$messageId'
    | '/post/$id'
    | '/to/$username'
    | '/user/$username'
    | '/groups/$tag/chat'
    | '/groups/$tag'
  id:
    | '__root__'
    | '/_marketing'
    | '/_private'
    | '/_public'
    | '/_social'
    | '/_marketing/about'
    | '/_private/groups'
    | '/_private/inbox'
    | '/_private/moderation'
    | '/_private/notifications'
    | '/_private/settings'
    | '/_public/banned'
    | '/_public/child-safety'
    | '/_public/login'
    | '/_public/privacy'
    | '/_public/register'
    | '/_public/social'
    | '/_public/terms'
    | '/_public/tiers'
    | '/_social/feed'
    | '/_social/notes'
    | '/groups/$tag'
    | '/_marketing/'
    | '/_private/inbox_/$messageId'
    | '/_social/post/$id'
    | '/_social/to/$username'
    | '/_social/user/$username'
    | '/groups/$tag/chat'
    | '/groups/$tag/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PrivateRoute: typeof PrivateRouteWithChildren
  PublicRoute: typeof PublicRouteWithChildren
  SocialRoute: typeof SocialRouteWithChildren
  GroupsTagRoute: typeof GroupsTagRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private': {
      id: '/_private'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PrivateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_social': {
      id: '/_social'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/about': {
      id: '/_marketing/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof MarketingAboutRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_private/groups': {
      id: '/_private/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof PrivateGroupsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/inbox': {
      id: '/_private/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof PrivateInboxRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/moderation': {
      id: '/_private/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof PrivateModerationRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/notifications': {
      id: '/_private/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof PrivateNotificationsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_private/settings': {
      id: '/_private/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof PrivateSettingsRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_public/banned': {
      id: '/_public/banned'
      path: '/banned'
      fullPath: '/banned'
      preLoaderRoute: typeof PublicBannedRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/child-safety': {
      id: '/_public/child-safety'
      path: '/child-safety'
      fullPath: '/child-safety'
      preLoaderRoute: typeof PublicChildSafetyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/login': {
      id: '/_public/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof PublicLoginRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/register': {
      id: '/_public/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof PublicRegisterRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/social': {
      id: '/_public/social'
      path: '/social'
      fullPath: '/social'
      preLoaderRoute: typeof PublicSocialRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/tiers': {
      id: '/_public/tiers'
      path: '/tiers'
      fullPath: '/tiers'
      preLoaderRoute: typeof PublicTiersRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_social/feed': {
      id: '/_social/feed'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof SocialFeedRouteImport
      parentRoute: typeof SocialRoute
    }
    '/_social/notes': {
      id: '/_social/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof SocialNotesRouteImport
      parentRoute: typeof SocialRoute
    }
    '/groups/$tag': {
      id: '/groups/$tag'
      path: '/groups/$tag'
      fullPath: '/groups/$tag'
      preLoaderRoute: typeof GroupsTagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_private/inbox_/$messageId': {
      id: '/_private/inbox_/$messageId'
      path: '/inbox/$messageId'
      fullPath: '/inbox/$messageId'
      preLoaderRoute: typeof PrivateInboxMessageIdRouteImport
      parentRoute: typeof PrivateRoute
    }
    '/_social/post/$id': {
      id: '/_social/post/$id'
      path: '/post/$id'
      fullPath: '/post/$id'
      preLoaderRoute: typeof SocialPostIdRouteImport
      parentRoute: typeof SocialRoute
    }
    '/_social/to/$username': {
      id: '/_social/to/$username'
      path: '/to/$username'
      fullPath: '/to/$username'
      preLoaderRoute: typeof SocialToUsernameRouteImport
      parentRoute: typeof SocialRoute
    }
    '/_social/user/$username': {
      id: '/_social/user/$username'
      path: '/user/$username'
      fullPath: '/user/$username'
      preLoaderRoute: typeof SocialUserUsernameRouteImport
      parentRoute: typeof SocialRoute
    }
    '/groups/$tag/': {
      id: '/groups/$tag/'
      path: '/'
      fullPath: '/groups/$tag/'
      preLoaderRoute: typeof GroupsTagIndexRouteImport
      parentRoute: typeof GroupsTagRoute
    }
    '/groups/$tag/chat': {
      id: '/groups/$tag/chat'
      path: '/chat'
      fullPath: '/groups/$tag/chat'
      preLoaderRoute: typeof GroupsTagChatRouteImport
      parentRoute: typeof GroupsTagRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingAboutRoute: typeof MarketingAboutRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingAboutRoute: MarketingAboutRoute,
  MarketingIndexRoute: MarketingIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

interface PrivateRouteChildren {
  PrivateGroupsRoute: typeof PrivateGroupsRoute
  PrivateInboxRoute: typeof PrivateInboxRoute
  PrivateModerationRoute: typeof PrivateModerationRoute
  PrivateNotificationsRoute: typeof PrivateNotificationsRoute
  PrivateSettingsRoute: typeof PrivateSettingsRoute
  PrivateInboxMessageIdRoute: typeof PrivateInboxMessageIdRoute
}

const PrivateRouteChildren: PrivateRouteChildren = {
  PrivateGroupsRoute: PrivateGroupsRoute,
  PrivateInboxRoute: PrivateInboxRoute,
  PrivateModerationRoute: PrivateModerationRoute,
  PrivateNotificationsRoute: PrivateNotificationsRoute,
  PrivateSettingsRoute: PrivateSettingsRoute,
  PrivateInboxMessageIdRoute: PrivateInboxMessageIdRoute,
}

const PrivateRouteWithChildren =
  PrivateRoute._addFileChildren(PrivateRouteChildren)

interface PublicRouteChildren {
  PublicBannedRoute: typeof PublicBannedRoute
  PublicChildSafetyRoute: typeof PublicChildSafetyRoute
  PublicLoginRoute: typeof PublicLoginRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicRegisterRoute: typeof PublicRegisterRoute
  PublicSocialRoute: typeof PublicSocialRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicTiersRoute: typeof PublicTiersRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBannedRoute: PublicBannedRoute,
  PublicChildSafetyRoute: PublicChildSafetyRoute,
  PublicLoginRoute: PublicLoginRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicRegisterRoute: PublicRegisterRoute,
  PublicSocialRoute: PublicSocialRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicTiersRoute: PublicTiersRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface SocialRouteChildren {
  SocialFeedRoute: typeof SocialFeedRoute
  SocialNotesRoute: typeof SocialNotesRoute
  SocialPostIdRoute: typeof SocialPostIdRoute
  SocialToUsernameRoute: typeof SocialToUsernameRoute
  SocialUserUsernameRoute: typeof SocialUserUsernameRoute
}

const SocialRouteChildren: SocialRouteChildren = {
  SocialFeedRoute: SocialFeedRoute,
  SocialNotesRoute: SocialNotesRoute,
  SocialPostIdRoute: SocialPostIdRoute,
  SocialToUsernameRoute: SocialToUsernameRoute,
  SocialUserUsernameRoute: SocialUserUsernameRoute,
}

const SocialRouteWithChildren =
  SocialRoute._addFileChildren(SocialRouteChildren)

interface GroupsTagRouteChildren {
  GroupsTagChatRoute: typeof GroupsTagChatRoute
  GroupsTagIndexRoute: typeof GroupsTagIndexRoute
}

const GroupsTagRouteChildren: GroupsTagRouteChildren = {
  GroupsTagChatRoute: GroupsTagChatRoute,
  GroupsTagIndexRoute: GroupsTagIndexRoute,
}

const GroupsTagRouteWithChildren = GroupsTagRoute._addFileChildren(
  GroupsTagRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PrivateRoute: PrivateRouteWithChildren,
  PublicRoute: PublicRouteWithChildren,
  SocialRoute: SocialRouteWithChildren,
  GroupsTagRoute: GroupsTagRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
