import {
  AnchorIcon,
  AtomIcon,
  BotIcon,
  BugIcon,
  CatIcon,
  CloudIcon,
  CoffeeIcon,
  CrownIcon,
  DogIcon,
  FlameIcon,
  Gamepad2Icon,
  GemIcon,
  GhostIcon,
  GlassesIcon,
  GraduationCapIcon,
  HeartIcon,
  LeafIcon,
  type LucideIcon,
  MicIcon,
  MoonIcon,
  MusicIcon,
  PencilIcon,
  PizzaIcon,
  RocketIcon,
  ShieldIcon,
  SkullIcon,
  SnowflakeIcon,
  SparklesIcon,
  StarIcon,
  SunIcon,
  SwordsIcon,
  TrophyIcon,
  ZapIcon,
} from "lucide-react";
import type { GroupAccent, GroupIcon } from "@/lib/group";

export const GROUP_ICON_MAP: Record<GroupIcon, LucideIcon> = {
  anchor: AnchorIcon,
  atom: AtomIcon,
  bot: BotIcon,
  bug: BugIcon,
  cat: CatIcon,
  cloud: CloudIcon,
  coffee: CoffeeIcon,
  crown: CrownIcon,
  dog: DogIcon,
  flame: FlameIcon,
  gamepad: Gamepad2Icon,
  gem: GemIcon,
  ghost: GhostIcon,
  glasses: GlassesIcon,
  "grad-cap": GraduationCapIcon,
  heart: HeartIcon,
  leaf: LeafIcon,
  mic: MicIcon,
  moon: MoonIcon,
  music: MusicIcon,
  pencil: PencilIcon,
  pizza: PizzaIcon,
  rocket: RocketIcon,
  shield: ShieldIcon,
  skull: SkullIcon,
  snowflake: SnowflakeIcon,
  sparkles: SparklesIcon,
  star: StarIcon,
  sun: SunIcon,
  swords: SwordsIcon,
  trophy: TrophyIcon,
  zap: ZapIcon,
};

export const GROUP_ACCENT_CLASSES: Record<GroupAccent, string> = {
  rose: "text-rose-500",
  amber: "text-amber-500",
  emerald: "text-emerald-500",
  sky: "text-sky-500",
  violet: "text-violet-500",
  pink: "text-pink-500",
};
