// Head/SEO helpers — the replacement for Next's `metadataBase` + metadata
// inheritance, which is what made every apps/www page emit ABSOLUTE og:url /
// og:image / canonical URLs. TanStack's `head()` has no such base, so URLs must
// be absolutised here: a relative og:image is unreliable for crawlers (Facebook,
// Discord, Twitter), and link previews are core to how umamin gets shared.
//
// `VITE_SITE_URL` is the canonical public origin (production: the same
// www.umamin.link host robots.txt + sitemap.xml advertise — mixing hosts across
// canonical/og/sitemap reads as duplicate content).

export const OG_IMAGE = "/opengraph-image.png";
export const TWITTER_IMAGE = "/twitter-image.png";

// Read per call rather than at module load: Vite still inlines the literal, and
// tests can stub the env.
function siteOrigin(): string {
  return (import.meta.env.VITE_SITE_URL ?? "").replace(/\/+$/, "");
}

/** Absolutise an app path against the canonical origin (pass-through if already absolute). */
export function absoluteUrl(path: string): string {
  if (/^[a-z][a-z0-9+.-]*:/i.test(path)) return path;
  const origin = siteOrigin();
  const suffix = path.startsWith("/") ? path : `/${path}`;
  return origin ? `${origin}${suffix}` : suffix;
}

type MetaTag = Record<string, string>;

type PageSeoInput = {
  title: string;
  description: string;
  /** App path for the self-referential canonical + og:url. Omit for pages that shouldn't advertise one. */
  path?: string;
  ogType?: "website" | "article" | "profile";
  /** `summary_large_image` also emits twitter:image; `summary` lets crawlers fall back to og:image. */
  twitterCard?: "summary" | "summary_large_image";
  /** e.g. "noindex, follow". Omitted → inherits the root's index,follow default. */
  robots?: string;
};

/**
 * One page's `head()` payload: title/description, the OG + Twitter card, and a
 * self-referential canonical. Every URL comes out absolute.
 *
 * og:image is re-declared on every page ON PURPOSE — head meta is deduped by
 * name/property with the deepest route winning, so a page that declares its own
 * og:* set must also name the image or the preview loses it (MEMORY:
 * og-image-shallow-merge).
 */
export function pageSeo({
  title,
  description,
  path,
  ogType = "website",
  twitterCard = "summary_large_image",
  robots,
}: PageSeoInput): { meta: MetaTag[]; links: { rel: string; href: string }[] } {
  const meta: MetaTag[] = [
    { title },
    { name: "description", content: description },
  ];

  if (robots) meta.push({ name: "robots", content: robots });

  meta.push(
    { property: "og:type", content: ogType },
    { property: "og:site_name", content: "Umamin" },
    { property: "og:title", content: title },
    { property: "og:description", content: description },
    { property: "og:image", content: absoluteUrl(OG_IMAGE) },
  );
  if (path) meta.push({ property: "og:url", content: absoluteUrl(path) });

  meta.push(
    { name: "twitter:card", content: twitterCard },
    { name: "twitter:title", content: title },
    { name: "twitter:description", content: description },
  );
  if (twitterCard === "summary_large_image") {
    meta.push({ name: "twitter:image", content: absoluteUrl(TWITTER_IMAGE) });
  }

  return {
    meta,
    // Canonical is per-page only: links are concatenated (not deduped by rel),
    // so a root-level canonical would stack a second one on every route.
    links: path ? [{ rel: "canonical", href: absoluteUrl(path) }] : [],
  };
}

// iOS standalone launch screens (portrait — the manifest locks orientation),
// ported from apps/www's appleWebApp.startupImage. Generated by
// store-assets/splash-gen.py; without these links the installed iOS PWA opens on
// a blank white screen.
const APPLE_SPLASH: Array<[width: number, height: number, ratio: number]> = [
  [375, 667, 2],
  [414, 736, 3],
  [375, 812, 3],
  [414, 896, 2],
  [414, 896, 3],
  [390, 844, 3],
  [428, 926, 3],
  [393, 852, 3],
  [430, 932, 3],
  [402, 874, 3],
  [440, 956, 3],
  [768, 1024, 2],
  [820, 1180, 2],
  [834, 1194, 2],
  [1024, 1366, 2],
];

export const appleSplashLinks = APPLE_SPLASH.map(([width, height, ratio]) => ({
  rel: "apple-touch-startup-image",
  href: `/splash/apple-splash-${width * ratio}-${height * ratio}.png`,
  media: `screen and (device-width: ${width}px) and (device-height: ${height}px) and (-webkit-device-pixel-ratio: ${ratio}) and (orientation: portrait)`,
}));
